title: N25 Blog
name: N25
domain: n25.uk
base: ""
url: "https://n25.uk"
description: "" 
remote_theme: "mmistakes/minimal-mistakes
twitter_username: n25sec
github_username: n25sec
github:
  is_project_page: false
language: en

# Category settings
jekyll-archives:
  enabled: 
    - categories
    - tags
  layout: archive
  permalinks:
    category: /category/:name/
    tag: /tag/:name/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-include-cache
  
